spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-drop

amazon:
  dynamodb:
    endpoint: "http://localhost:8000"
  aws:
    accessKey: "fakeMyKeyId"
    secretKey: "fakeSecretAccessKey"
    region: "eu-west-2"